version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5174:5173"
    volumes:
      - /app/node_modules
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5175:5173"
    volumes:
      - /app/node_modules
      - .:/app
